apps/starter/craco.config.js, apps/starter/package.json, apps/starter/src/ensemble/home.yaml, packages/framework/package.json, packages/framework/src/data/fetcher.ts, packages/framework/src/data/index.ts, packages/framework/src/hooks/useEnsembleState.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/index.ts, packages/framework/src/models.ts, packages/framework/src/parser.ts, packages/framework/src/state.ts, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/runtime.tsx, pnpm-lock.yaml
=> Initial data fetching and bind to widget

.husky/pre-commit, apps/starter/package.json, package.json, packages/framework/package.json, packages/runtime/package.json, pnpm-lock.yaml, turbo.json
=> Autofix lint problems on commit

apps/starter/src/App.tsx, apps/starter/src/ensemble/collections.yaml, packages/runtime/package.json, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/runtime/navigate.ts, packages/runtime/src/runtime/runtime.tsx, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/Markdown.tsx, packages/runtime/src/widgets/Text.tsx, pnpm-lock.yaml
=> Add support for multiple screens

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md, README.md, packages/runtime/src/widgets/Card.tsx
=> added card widget

apps/starter/src/ensemble/usersAndGroups.yaml, packages/runtime/src/widgets/Card.tsx
- Replaces grid in user management with grid view
- Clean up Card styling implementation
=> Add grid to users and groups page

apps/starter/src/ensemble/dashboard.yaml, apps/starter/src/ensemble/usersAndGroups.yaml, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/runtime/navigate.ts, packages/runtime/src/widgets/Avatar/Avatar.tsx
- Ensure navigate screen hook is relative to root path
- Sync location with menu state
=> Use root path for navigate screen and sync with menu state

.github/pull_request_template.md, packages/framework/src/__tests__/evaluate.test.ts, packages/framework/src/evaluate.ts, packages/framework/src/hooks/__tests__/useExecuteCode.test.ts, packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/state.ts, packages/framework/src/storage.ts
- Adds ensemble.storage.set and ensemble.storage.get capabilities
Closes #10
=> Implement basic ensemble storage API

apps/starter/src/ensemble/usersAndGroups.yaml, packages/framework/src/data/fetcher.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/shared/models.ts, packages/framework/src/state.ts, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/screen.tsx
- Handle headers on API model
- Refactor screen.onLoad to include action chaining
- Allow passing additional context in executeCode for action chaining
Closes #
=> Fix API Handling

apps/starter/src/ensemble/usersAndGroups.yaml, packages/runtime/src/widgets/Conditional.tsx
=> Fix deepcopy when unwraping widgets in Conditional

packages/framework/src/shared/actions.ts, packages/runtime/package.json, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useShowToast.tsx, pnpm-lock.yaml
- Use react-toastify to implement showToast action
Closes #74
=> Add showToast action

apps/starter/src/ensemble/collections.yaml, packages/runtime/src/runtime/screen.tsx, packages/runtime/src/widgets/MultiSelect.tsx
- Bind multi select values and options
- 
Closes #
=> Bind multi select values and options

apps/starter/src/ensemble/askEmbrace.yaml, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/index.ts
Added a checkbox widget
#45 
Closes #
#45
=> added checkbox widget

packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> fix invokeApi callback running infinitely

packages/runtime/src/util/types.ts, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Row.tsx, packages/runtime/src/widgets/Search.tsx
Some basic styles changed for more control over Column, Row and Search styling
Closes #
=> basic styles changed for Column, Row and Search

.changeset/wild-yaks-jog.md, apps/starter/CHANGELOG.md, apps/starter/package.json, packages/framework/CHANGELOG.md, packages/framework/package.json, packages/runtime/CHANGELOG.md, packages/runtime/package.json
=> Release v0.0.3

.changeset/nice-laws-refuse.md, apps/starter/src/ensemble/askEmbrace.yaml, packages/framework/.eslintrc.js, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useWidgetState.ts, packages/framework/src/state.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Avatar/Avatar.tsx, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/Dropdown.tsx, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Icon.tsx, packages/runtime/src/widgets/Image.tsx, packages/runtime/src/widgets/Markdown.tsx, packages/runtime/src/widgets/MultiSelect.tsx, packages/runtime/src/widgets/TabBar.tsx, packages/runtime/src/widgets/Tag.tsx, packages/runtime/src/widgets/Text.tsx
- Updates returned value of useRegisterBindings to be the value in state
- Updates usePickFiles to invoke callback only when state is updated
Closes #129
=> Ensure state is resolved before firing pickFiles onComplete callback

apps/starter/src/ensemble/dashboard.yaml, packages/runtime/src/widgets/Charts/StackBarChart.tsx
Closes https://github.com/EnsembleUI/ensemble-react/issues/32
=> Added labels in horizontal stacked bar chart

apps/starter/README.md, packages/runtime/src/index.tsx
- Update README with steps on how to get started with React
- Expose WidgetRegistry through runtime index
Closes #
=> Update README with steps on getting started

.changeset/twelve-hotels-tan.md, packages/framework/package.json, packages/framework/src/hooks/index.ts, packages/framework/src/hooks/useData.ts, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useWidgetState.ts, packages/framework/src/state.ts, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, pnpm-lock.yaml
=> Performance fixes

packages/runtime/src/util/types.ts, packages/runtime/src/widgets/Icon.tsx
Added Icon styles for backgroundColors, border, and padding , margin 
Closes #
=> Dashboard atlas styles

apps/starter/src/ensemble/createGroup.yaml, apps/starter/src/ensemble/usersAndGroups.yaml, packages/framework/src/evaluate.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/shared/actions.ts, packages/framework/src/state.ts, packages/framework/src/storage.ts, packages/runtime/src/runtime/entry.tsx, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/hooks/useNavigateScreen.ts, packages/runtime/src/runtime/screen.tsx
=> Support passing inputs into screen

apps/starter/src/ensemble/askEmbrace.yaml, apps/starter/src/ensemble/createGroup.yaml, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/footer.tsx, packages/runtime/src/runtime/header.tsx, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/runtime/modal.tsx, packages/runtime/src/runtime/screen.tsx
=> add sticky Header and Footer in view

packages/runtime/src/widgets/Tag.tsx
Some stylistic changes for Tag
Closes #
=> added expression type for backgroundColor

packages/runtime/src/runtime/footer.tsx, packages/runtime/src/widgets/Divider.tsx
Resolves the vertical divider issue in Atlas dashboard
Closes #
=>  vertcial divider

apps/starter/src/ensemble/usersAndGroups.yaml, packages/runtime/src/widgets/Tag.tsx, packages/runtime/src/widgets/Text.tsx
1. Added text Styles to Tag widget
2. Added color as expression in Text widget.
This PR closes the JIRA ticket [Nav2-48](https://jira.atlaslabs.work/browse/NAV2-48) for ensemble atlas
Closes #
=> Nav2-42 Tag styles

apps/starter/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Charts/StackBarChart.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Search.tsx
1. Fixes the labels displaying on top of y-axis in stack bar chart.
2. Fixes the search bar back color.
3. Fixes the borderRadius for bars in Stack Bar chart.
Closes #
=> Fix for Nav2-46 and 45 in Atlas-React

.changeset/witty-nails-travel.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/__tests__/__resources__/mycustomwidget.yaml, packages/framework/src/__tests__/parser.test.ts, packages/framework/src/parser.ts, packages/runtime/src/widgets/Charts/DoughnutChart.tsx, packages/runtime/src/widgets/Charts/LineChart.tsx, packages/runtime/src/widgets/Charts/StackBarChart.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Row.tsx
=> Fix chart sizing and add data-testids for rows and columns

.changeset/red-dryers-breathe.md, packages/framework/src/evaluate.ts, packages/framework/src/hooks/useTemplateData.ts, packages/framework/src/hooks/useWidgetId.ts, packages/framework/src/shared/common.ts, packages/framework/src/state/widget.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/widgets/Conditional.tsx, packages/runtime/src/widgets/TabBar.tsx
- Check widget IDs are valid javascript and log error if not the case
- Improve error reporting from evaluate
- Require all invocations of evaluate to catch the error
-
Closes #
=> Require explicit error handling from evaluate

.changeset/thin-grapes-notice.md, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useWidgetId.ts
- Use ref callback instead of ref object to handle data-testid assignment
Closes #
=> Use ref callback instead of ref object to handle data-testid assignment

apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/package.json, packages/runtime/src/widgets/Charts/StackBarChart.tsx, pnpm-lock.yaml
Added support for adding labels inside the stacked bar charts 
Closes #
This closes the [NAV2-49](https://jira.atlaslabs.work/browse/NAV2-49) JIRA ticket
=> added chartjs-datalabels-plugin support for stacked chart

apps/starter/src/ensemble/screens/dashboard.yaml, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/evaluate.ts, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts
Allows dev to use Global Block to define their Functions and variables there.
#158 
Closes #
#158
=> Global block

.changeset/tough-dodos-add.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/hooks/useWidgetId.ts, packages/runtime/src/widgets/Text.tsx
- Handle widget IDs with expressions
Closes #187
=> Evaluate widget ids as expressions

.changeset/green-readers-sip.md, apps/starter/src/App.tsx, apps/starter/src/ensemble/screens/usersAndGroups.yaml, apps/starter/src/ensemble/scripts/test.js, packages/framework/src/__tests__/parser.test.ts, packages/framework/src/evaluate.ts, packages/framework/src/parser.ts, packages/framework/src/shared/actions.ts, packages/framework/src/shared/dto.ts, packages/framework/src/shared/models.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- Include scripts as part of application model
- Execute script contents from executeCode
Closes #159
=> Support executing script from file

.changeset/rude-news-beam.md, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/hooks/useTemplateData.ts, packages/framework/src/state/widget.ts, packages/framework/src/storage.ts, packages/runtime/package.json, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/TabBar.tsx, packages/runtime/src/widgets/Tag.tsx
- Re-evaluates bindings when data change
- Fixes chart config evaluation to happen before render
- Small polish for Tag and Tabbar
Closes #194
=> Fix bindings not updating on data change

.changeset/plenty-hairs-approve.md, packages/framework/src/evaluate.ts, packages/framework/src/hooks/useTemplateData.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/TabBar.tsx
- Adds ability to sort and filter for DataGrid
Closes #193
=> Add ability to sort and filter for DataGrid

.changeset/flat-parrots-itch.md, apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/src/widgets/Charts/index.tsx
- Set expiry for chart config eval
- Short circuit infinite render loop
- 
Closes #199
=> Remove infinite render loop from chart config evaluation

.changeset/afraid-walls-bow.md, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/modal.tsx, packages/runtime/src/runtime/screen.tsx
- Add isModal flag to screen
- Skip screen content height calculation if modal since height is determined by modal
Closes #202
=> Skip screen height calculation if modal

.changeset/chilly-spies-give.md, packages/runtime/src/runtime/entry.tsx
- Skip forced navigation if path is not empty
Closes #213
=> Skip navigating to selected screen if path is not empty

.changeset/tough-pans-give.md, packages/framework/src/__tests__/evaluate.test.ts, packages/framework/src/evaluate.ts, packages/framework/src/hooks/index.ts, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/hooks/useEvaluate.ts, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/hooks/useTemplateData.ts, packages/framework/src/index.ts, packages/framework/src/state/widget.ts, packages/framework/src/storage.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Charts/index.tsx
- Refactor ensemble.storage under atom context to update dependent atoms
- Deprecate non-atom context evaluations
Closes #203
=> Trigger rerender on updates to ensemble.storage using atom context

.changeset/four-dragons-type.md, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/hooks/useTemplateData.ts, packages/framework/src/state/widget.ts
=> Fix stale storage reference

.changeset/shiny-seas-shave.md, packages/runtime/package.json, pnpm-lock.yaml
=> Fix runtime package dependency

.changeset/curvy-planes-relax.md, packages/runtime/package.json
=> Revert dependency change

.changeset/ten-lions-train.md, apps/starter/src/ensemble/screens/askEmbrace.yaml, packages/framework/src/parser.ts, packages/runtime/src/widgets/ToggleButton.tsx, packages/runtime/src/widgets/index.ts
=> add ToggleButton widget

.changeset/popular-socks-study.md, apps/starter/src/ensemble/screens/askEmbrace.yaml, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Row.tsx
=> Add item-template support in Row and Column

.changeset/slow-carpets-camp.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/state/screen.ts, packages/framework/src/state/widget.ts, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/hooks/useNavigateScreen.ts, packages/runtime/src/runtime/screen.tsx
- Ensure inputs are evaluated before navigating
- Update widget binding fn to include screen inputs
Closes #229
=> Evaluate screen inputs before navigating

.changeset/clean-tools-mate.md, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/hooks/useNavigateScreen.ts, packages/runtime/src/widgets/Tag.tsx
- Deep clone inputs so evaluation remains local to hook instance
Closes #234
=> Deep clone navigate inputs before evaluation

.changeset/cuddly-carrots-trade.md, packages/framework/src/evaluate.ts, packages/framework/src/state/application.ts, packages/framework/src/state/widget.ts, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Row.tsx, packages/runtime/src/widgets/Search.tsx, packages/runtime/src/widgets/TabBar.tsx, packages/runtime/src/widgets/Text.tsx
- Fix how theme tokens are populated during evaluation
- Update a few core widgets to use evaluated styles
Closes #
=> Fixes for theming

.changeset/twenty-numbers-float.md, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/screen.tsx
- Move run once guarantee from executeCode to OnLoadAction
Closes #239
=> Move run once guarantee from executeCode to OnLoadAction

apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/Dropdown.tsx, packages/runtime/src/widgets/Stepper/Stepper.tsx
- Removed margin for dropdown
- Added gap property for button widget 
Closes #
=> added minor changes for button and dropdown widgets

.changeset/flat-wolves-change.md, .changeset/soft-geese-breathe.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, apps/starter/src/ensemble/widgets/Header.yaml, packages/framework/src/data/fetcher.ts, packages/framework/src/hooks/useEvaluate.ts, packages/framework/src/shared/models.ts, packages/runtime/package.json, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Conditional.tsx, packages/runtime/src/widgets/Row.tsx, packages/runtime/src/widgets/Search.tsx, packages/runtime/src/widgets/TabBar.tsx, packages/runtime/src/widgets/__tests__/Conditional.test.tsx, pnpm-lock.yaml
- Expose additional action hooks on Search
- Update data fetcher to resolve URI and param bindings properly
- Remove screen context from TabBar and Conditional render dependencies
- Exclude nested widgets from registered bindings
Closes #96
=> Enhance Search widget to search via API

.changeset/twenty-penguins-design.md, apps/starter/src/ensemble/screens/askEmbrace.yaml, packages/runtime/src/widgets/Divider.tsx, packages/runtime/src/widgets/Icon.tsx, packages/runtime/src/widgets/ToggleButton.tsx
- Using regsitered bindings for Divider and icon widgtets
Closes #
=> replaced props with registered bindings for divider and icon

.changeset/witty-feet-flow.md
=> Fix patch levels on #243

.changeset/wicked-jobs-retire.md, packages/runtime/src/widgets/ToggleButton.tsx
=> Add support for ToggleButton data-testid

.changeset/purple-poems-shop.md, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/state/user.ts, packages/framework/src/state/widget.ts
- Adds user atom
- Adds it to binding atom evaluation
Closes #12
=> Add user atom

packages/framework/src/state/index.ts
=> Fix user export

.changeset/two-gifts-itch.md, apps/starter/src/ensemble/screens/askEmbrace.yaml, apps/starter/src/ensemble/screens/createCollection.yaml, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/runtime/src/runtime/modal.tsx, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/Divider.tsx, packages/runtime/src/widgets/Dropdown.tsx, packages/runtime/src/widgets/Form/Form.tsx, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Progress.tsx, packages/runtime/src/widgets/Row.tsx, packages/runtime/src/widgets/Tag.tsx
- Exposed currentIndex and templateLength properties for item template
- Added property center for position in modal.
- A stylistic addition in textInput 
- Added Static Progress indication for Progress Bar and some properties addition 
- Support for Expressions in DataGrid header styles
Closes #
=> exposed index and lenght for iterating array

.changeset/dry-steaks-count.md, apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/src/widgets/Stepper/Stepper.tsx
- added stepper style fixes
- fixed connector inActive State color
This was an issue reported by Jairo in jira ticket
Closes #
=> Stepper style fixes

.changeset/mean-trainers-mate.md, README.md, apps/starter/README.md, apps/starter/src/App.tsx, apps/starter/src/ensemble-config.yaml, apps/starter/src/ensemble/screens/home.yaml, apps/starter/src/ensemble/screens/socialLogin.yaml, package.json, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/parser.ts, packages/framework/src/shared/dto.ts, packages/framework/src/shared/models.ts, packages/framework/src/state/application.ts, packages/framework/src/state/widget.ts, packages/runtime/package.json, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/SignInWithGoogle.tsx, packages/runtime/src/widgets/index.ts, pnpm-lock.yaml
Functionality for the google login
Created a custom widget for google login
=> 252 implement social login widget2

.changeset/afraid-yaks-cough.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/evaluate.ts, packages/runtime/src/runtime/screen.tsx
- Fixes the context for invoke API under onLoad action. 
#265 
Closes #
#265
=> Fixed inputs not being recognized for onLoad action

.changeset/fair-islands-cheer.md, apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
Added onTap action handler on each row of DataGrid widget
Closes #
closes: #233
=> feat: added onTap action handler on each row on datagrid

.changeset/chilled-maps-enjoy.md, .changeset/red-lobsters-eat.md, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/widgets/GridView.tsx
=> Support base pathname on Ensemble app

.changeset/nice-geckos-cheat.md, apps/starter/src/ensemble/screens/createGroup.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- Fixed the ensemble storage not recognized in the context for invokeAPI 
Closes #
=> Fix invoke api context

.changeset/poor-bugs-doubt.md, apps/starter/src/ensemble/screens/askEmbrace.yaml, apps/starter/src/ensemble/theme.yaml, packages/framework/src/hooks/index.ts, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useStyleNames.ts, packages/framework/src/hooks/useThemeContext.ts
=> add useThemeContext hook to fix style names not being applied

packages/runtime/src/runtime/screen.tsx
- Was causing infinite-re-renders on the enrollment screen for execute code
no paticular ticket
Closes #
=> a small causing infinit-re-render for executeCode

.changeset/clever-needles-give.md, apps/starter/src/ensemble/screens/dashboard.yaml, packages/runtime/src/widgets/Charts/BarChart.tsx, packages/runtime/src/widgets/Charts/DoughnutChart.tsx, packages/runtime/src/widgets/Charts/LineChart.tsx, packages/runtime/src/widgets/Charts/StackBarChart.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Charts/utils/getMergedOptions.ts
=> Fix chart options

.changeset/fresh-insects-sniff.md, apps/starter/src/ensemble/screens/usersAndGroups.yaml, packages/framework/src/data/fetcher.ts, packages/framework/src/data/index.ts, packages/framework/src/hooks/useEvaluate.ts, packages/framework/src/hooks/useTemplateData.ts, packages/framework/src/state/widget.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/LoadingContainer.tsx, packages/runtime/src/widgets/index.ts
- Add LoadingContainer widget
- Add isLoading state to EnsembleResponse
- Fix expression evaluation return null instead of expression
Closes #160
=> Add LoadingContainer widget

.changeset/loud-weeks-pay.md, packages/framework/src/hooks/useWidgetId.ts, packages/runtime/src/widgets/Skeleton.tsx, packages/runtime/src/widgets/ToggleButton.tsx, packages/runtime/src/widgets/index.ts
- Fix test id evaluation
- Add skeleton widget
Closes #119
=> Implement Skeleton widget

.changeset/chatty-donuts-occur.md, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/state/user.ts, packages/runtime/src/runtime/menu.tsx
- Remove getoninit option from storage atoms
- Add testId attribute support on menu items
- 
Closes #282
=> Remove getoninit from storage atoms

packages/framework/src/state/widget.ts, packages/runtime/src/widgets/Charts/BarChart.tsx
=> Add data labels plugin for BarChart

.changeset/nervous-grapes-join.md, apps/starter/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Search.tsx
Support expression evaluation inside placeholder string of search widgets
Closes #
closes #288
=> fix: support expression evaluate inside placeholder of search widget

.changeset/small-papayas-vanish.md, .github/pull_request_template.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/hooks/useWidgetId.ts, packages/runtime/src/widgets/Dropdown.tsx
- Adds new root element for ref and HTML attrs
- Fixes behavior with default value
- Adds support for autoComplete
Closes #
=> Fix small issues with Dropdown

.changeset/fair-drinks-retire.md, packages/runtime/src/widgets/Stepper/Stepper.tsx
- Fixes rootRef for Stepper widget
- Adds an active step indicator below the label
Closes #
=> Add activeStep indicator to Stepper widget

.changeset/orange-knives-type.md, apps/kitchen-sink/src/ensemble/screens/menu.yaml, packages/runtime/src/runtime/menu.tsx
Added `useRegisterBindings` to support theme values into sidebar menu
Closes #
closes #296
=> added support of theme values into sidebar menu

.changeset/tender-plums-crash.md, packages/framework/src/parser.ts, packages/runtime/src/widgets/Charts/index.tsx
charts is crashed when used useRegisterBindings
Closes #
closes #317
=> replace useRegisterBindings with useHtmlPassThrough in chart s

.changeset/chilly-pants-ring.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/__tests__/evaluate.test.ts, packages/framework/src/evaluate.ts
=> support returning last statement of multiline js

.changeset/chatty-cobras-march.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
exposed user object in useExcuteCode / executeCode action
Closes #
=> user object exposed in executeCode hook

.changeset/metal-panthers-argue.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/footer.tsx, packages/runtime/src/runtime/header.tsx, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Row.tsx
- Added onTap event to Row widget 
- Modified hover behavior to pointer
Closes #
=> added onClick event to Row widget

.changeset/large-jeans-lie.md, packages/runtime/src/runtime/entry.tsx
=> Fix entry navigation for apps without menu

.changeset/heavy-walls-flow.md, apps/kitchen-sink/src/App.tsx, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Collapsible.tsx, packages/runtime/src/widgets/Icon.tsx, packages/runtime/src/widgets/index.ts, pnpm-lock.yaml
Added a collapsible widget with functionality of accordion.
Features:
Item template
can pass custom icons
can change header and content background color
Closes #
closes #297
=> added collapsible widget

.changeset/silly-llamas-occur.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/MultiSelect.tsx, packages/runtime/src/widgets/Tag.tsx
- added ability for users to select a particular row or all rows 
- exposed onRowSelect action
https://github.com/EnsembleUI/ensemble-react/assets/62849614/c361fb73-c452-40a6-8a5b-a44c7092f93d
Closes #
=> Data grid row selection

packages/runtime/src/widgets/Form/Form.tsx
=> Fix form rendering children

.changeset/healthy-camels-shake.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/PopupMenu.tsx
added item-template inside the popup menu widget
Closes #
closes #332
=> added item-template inside the popup menu widget

packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Divider.tsx
added basic styling changes to showDialog and support for useRegsiteredBindings to divider
Closes #
=> added styles for showDialogs

.changeset/smooth-buses-allow.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/PopupMenu.tsx
=> fix: added widget in popup label

.changeset/six-carrots-remain.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Enhance options for showdialog that include `title` and  `hideCloseIcon` properties
Closes #
closes #340
=> enhance options for showdialog

.changeset/wise-points-switch.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/FormItem.tsx
Added widget support feature in form items
Closes #
closes #338
=> added widget support in form items

.changeset/hot-moons-work.md, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Icon.tsx
=> Add onTap to Icon

.changeset/tricky-cooks-retire.md, packages/framework/src/evaluate/context.ts, packages/framework/src/evaluate/evaluate.ts, packages/framework/src/evaluate/index.ts, packages/framework/src/index.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Icon.tsx
=> Small fixes from scope propagation refactor

.changeset/mean-pets-smoke.md, .changeset/popular-wolves-grin.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/hooks/useCustomScope.tsx, packages/framework/src/hooks/useTemplateData.ts, packages/runtime/src/runtime/customWidget.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/modal.tsx, packages/runtime/src/widgets/Conditional.tsx
=> Various scope fixes

apps/kitchen-sink/src/ensemble/screens/widgets.yaml, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/runtime/customWidget.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Column.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Icon.tsx, packages/runtime/src/widgets/PopupMenu.tsx, packages/runtime/src/widgets/Progress.tsx, packages/runtime/src/widgets/Row.tsx, packages/runtime/src/widgets/Skeleton.tsx
- added onTap to have access to local scope 
- similar for pickFiles action
Closes #
=> OnTap-updates

.changeset/smooth-baboons-love.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/package.json, packages/framework/src/date/dateFormatter.ts, pnpm-lock.yaml
- added getDaysDifference, getMonthsDifference, getYearsDifference in date formatter api
Closes #
=> Add date difference calculations to Ensemble Date Formatter

.changeset/shiny-bags-watch.md, packages/framework/src/shared/models.ts, packages/runtime/src/runtime/runtime.tsx, packages/runtime/src/widgets/Conditional.tsx
=> Render conditional widgets with unique keys

.changeset/afraid-points-beam.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/data/fetcher.ts, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/GridView.tsx
Added feature for support of infinite scroll.
Closes #
closes #279
=> support infinite scroll

apps/kitchen-sink/.eslintrc.js, apps/kitchen-sink/src/ensemble/screens/home.yaml, apps/kitchen-sink/src/ensemble/scripts/test.js
=> Add example of calling function defined in global script

.changeset/eighty-adults-exercise.md, packages/runtime/src/runtime/menu.tsx
=> Fix selected styling on menu

.changeset/short-carrots-push.md, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
set default scrollwidth to max-content
Closes #
=> allow max-content as default scrollWidth

.changeset/soft-beans-yell.md, packages/runtime/src/widgets/DataGrid/DataCell.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> Include row index in data cell context

.changeset/eleven-panthers-complain.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/shared/styles.ts, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Form/MultiSelect.tsx
=> Update MultiSelect widget

.changeset/breezy-crews-rhyme.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Progress.tsx
=> Fix progress styles

.changeset/chilled-students-clean.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Icon.tsx
- added onHover action to Icon widget
Closes #
=> added onHover action to Icon Widget

.changeset/forty-berries-rest.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Collapsible.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/GridView.tsx
Added blockage of unnecessary event passthrough on datarow on tap
Closes #396
=> fix: added blockage of unnecessary event passthrough on datarow

.changeset/sixty-singers-change.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/ToggleButton.tsx
- updated a minor styling for toggle button
Closes #
=> toggle button styles update

apps/kitchen-sink/src/ensemble/screens/layouts.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Flow.tsx, packages/runtime/src/widgets/index.ts
=> Flow-Widget

.github/workflows/firebase-hosting-merge.yml, .gitignore, apps/preview/src/AppPreview.tsx, package.json, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/shared/coreSchema.ts, packages/runtime/src/shared/hasSchema.ts, packages/runtime/src/shared/layoutSchema.ts, packages/runtime/src/shared/screenSchema.ts, packages/runtime/src/shared/styleSchema.ts, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Avatar/Avatar.tsx, packages/runtime/src/widgets/Form/Date/Date.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Form/MultiSelect.tsx, packages/runtime/src/widgets/Image.tsx, packages/runtime/src/widgets/PopupMenu.tsx, packages/runtime/src/widgets/ToggleButton.tsx, packages/tsconfig/base.json, pnpm-lock.yaml, scripts/generateSchema.ts
=> Publish ensemble-react schema in preview

packages/eslint-config-custom/react.js, packages/framework/src/shared/actions.ts, packages/framework/src/shared/models.ts, packages/runtime/src/shared/coreSchema.ts, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/LoadingContainer.tsx, packages/runtime/src/widgets/PopupMenu.tsx, scripts/generateSchema.ts
=> Fix schema generation refs

.changeset/pretty-apes-fly.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataCell.tsx
=> Fix bad merge erasing data grid row index

.changeset/slow-pigs-occur.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/TabBar.tsx
enhance style options for tabBar
Closes #226
=> enhance style options for tabBar

.changeset/dry-penguins-appear.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Switch.tsx, packages/runtime/src/widgets/index.ts
introduced new widget - switch
Closes #413
=> fix: added switch widget

.changeset/ninety-cats-swim.md, apps/kitchen-sink/src/ensemble/screens/help.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/navigation.tsx
=> add navigateBack action

.changeset/lazy-colts-relate.md, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Flex.tsx, packages/runtime/src/widgets/index.ts
Added support for flex widget
Closes #414
=> flex widget implementation

.changeset/friendly-scissors-behave.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Slider.tsx, packages/runtime/src/widgets/index.ts
added support of slider widget
Closes #412
=> fix: slider widget

.changeset/orange-horses-act.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, apps/starter/src/ensemble/screens/home.yaml, apps/starter/src/ensemble/widgets/Header.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/invokeApi.tsx
=> fix casing "invokeApi" to "invokeAPI"

apps/kitchen-sink/src/ensemble/screens/layouts.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Spacer.tsx, packages/runtime/src/widgets/index.ts
=> added spacer widget

apps/preview/firebase.json, packages/framework/src/shared/actions.ts, scripts/generateSchema.ts
=> Allow CORS for public json files in preview app

.changeset/grumpy-goats-begin.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/package.json, packages/runtime/src/widgets/ImageCropper.tsx, packages/runtime/src/widgets/index.ts, pnpm-lock.yaml
Image cropper widget
Closes #56 #411
=> feat: imagecropper widget

.changeset/polite-boxes-destroy.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigteExternalScreen.ts, packages/runtime/src/runtime/navigation.tsx
added navigateExternalScreen api
Closes #445
=> fix: added navigateExternalScreen api

.changeset/eleven-olives-drive.md, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, packages/runtime/src/shared/coreSchema.ts, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/FittedColumn.tsx, packages/runtime/src/widgets/FittedRow.tsx, packages/runtime/src/widgets/index.ts
=> add FittedRow and FittedColumn widgets

.changeset/orange-cobras-search.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Icon.tsx
1. added onMouseEnter and onMouseLeave actions
2. fixed an issue of modal interferring with Icon to trigger onMouseLeave
Closes #
=> FEATURE: ICON-Widget

apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Button.tsx
=> added disabled property for button

packages/framework/src/shared/actions.ts, packages/framework/tsdoc.json, packages/runtime/src/shared/types.ts, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/Skeleton.tsx, packages/runtime/src/widgets/Text.tsx, packages/runtime/tsdoc.json, packages/tsconfig/tsdoc.json
=> More studio schema fixes

packages/framework/src/hooks/useHtmlPassThrough.tsx, packages/framework/src/index.ts, packages/framework/src/loader.ts, packages/framework/src/parser.ts, packages/framework/src/serializer.ts, packages/runtime/src/widgets/Search.tsx, pnpm-lock.yaml
=> Preview fixes for studio integration

packages/runtime/src/runtime/runtime.tsx, packages/runtime/src/shared/coreSchema.ts, packages/runtime/src/widgets/Card.tsx
=> Schema fixes continued

.changeset/polite-elephants-promise.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/screen.tsx
Added support for styles in screen view
Closes #463
=> feat: added styles support in screen view

.changeset/brave-rice-wonder.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Stepper/Stepper.tsx
- Trying to fix activeStepIndex to support expressions 
Closes #
=> Stepper Feature

.changeset/fuzzy-yaks-deny.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useNavigateUrl.ts
- added support for url to be evaluated if an expression 
Closes #
=> added support for expressions in screen url for navigate url

.changeset/mighty-dots-move.md, packages/framework/src/data/fetcher.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigateUrl.ts, packages/runtime/src/runtime/hooks/useNavigteExternalScreen.ts
=> Various fixes in actions

.changeset/olive-needles-double.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/framework/src/hooks/useStyleNames.ts, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Search.tsx
=> Add action in checkbox

.changeset/smooth-hairs-scream.md, packages/framework/src/evaluate/binding.ts
=> Update acorn ECMAScript version to 2020 for optional chaining and nullish coalescing

.changeset/many-shrimps-fetch.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/package.json, packages/runtime/src/widgets/Charts/BarChart.tsx, packages/runtime/src/widgets/Charts/DoughnutChart.tsx, packages/runtime/src/widgets/Charts/LineChart.tsx, packages/runtime/src/widgets/Charts/StackBarChart.tsx, packages/runtime/src/widgets/Charts/index.tsx, pnpm-lock.yaml
Added support to accept plugins in line and doughnut charts
Closes #468
=> fix: added plugins in line and doughnut chart

.changeset/good-tomatoes-try.md, packages/framework/src/hooks/useRegisterBindings.ts, packages/runtime/src/widgets/Button.tsx
=> Add click callback to Button

.changeset/tasty-grapes-repair.md, packages/runtime/src/runtime/screen.tsx
=> Re-render screen if path changes

.changeset/hot-dingos-clap.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> add ability to pass DataColumn's label as a widget too

.changeset/purple-tomatoes-argue.md, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> Handle nullish label in DataColumn

.changeset/tame-pants-think.md, packages/framework/src/state/screen.ts, packages/runtime/src/runtime/invokeApi.tsx, packages/runtime/src/widgets/Search.tsx
=> Fix stale data in ensemble.invokeAPI

.changeset/bright-dodos-guess.md, packages/framework/src/data/fetcher.ts
=> Fix forced string coercion in data fetcher

.changeset/curvy-actors-complain.md, packages/runtime/src/widgets/Charts/BarChart.tsx, packages/runtime/src/widgets/Charts/DoughnutChart.tsx, packages/runtime/src/widgets/Charts/LineChart.tsx, packages/runtime/src/widgets/Charts/StackBarChart.tsx, packages/runtime/src/widgets/Charts/index.tsx, packages/runtime/src/widgets/Icon.tsx
=> Register ChartDataLabels globally and allow option to disable

.changeset/curvy-icons-shake.md, packages/runtime/src/widgets/Image.tsx
=> Add ondrag handler for Image

.changeset/popular-ligers-agree.md, .changeset/serious-foxes-clean.md, packages/framework/src/data/fetcher.ts, packages/framework/src/evaluate/evaluate.ts, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/state/application.ts, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/Form/TextInput.tsx
=> Debounce state changes from TextInput

.changeset/clever-eyes-ring.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> Add ensemble env to imperative invokeAPI

.changeset/modern-forks-jog.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/Date/Date.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Form/MultiSelect.tsx, packages/runtime/src/widgets/Form/Radio.tsx
Receive updated values from form elements
Closes #
=> fix: receive updated values from form elements

.changeset/rude-rice-fly.md, apps/kitchen-sink/src/ensemble/screens/customWidgets.yaml, packages/framework/src/date/dateFormatter.ts
Add `humanize` method to ensemble formatter
Use it like `ensemble.formatter.now().humanize(date)`
Closes #
=> add humanize method in ensemble.formatter

.changeset/tasty-frogs-pretend.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for actionGroup API
Closes #507
=> fix: added support for actionGroup action

.changeset/moody-tips-care.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
Added support for onPageChange action handler in datagrid
Closes #509
=> fix: added support for onPageChange action in datagrid

.changeset/thick-islands-cough.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Radio.tsx
Fix `value` of Radio being initialized as "undefined"
Before:
After:
Closes #
=> Set value of Radio as undefined instead of "undefined"

.changeset/thick-ants-share.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useNavigteExternalScreen.ts
Pass invokeApi response to navigateExternalScreen
Closes #512
=> fix: pass invokeApi response to navigateExternalScreen

.changeset/young-timers-drum.md, packages/runtime/src/widgets/ToggleButton.tsx
Fix toggle button value change bindings
Closes #520
=> fix: toggle button value change bindings

packages/runtime/src/shared/coreSchema.ts, scripts/generateSchema.ts
=> More react schema fixes

.changeset/hot-cheetahs-camp.md, apps/kitchen-sink/src/App.tsx, apps/kitchen-sink/src/ensemble/screens/home.yaml, apps/kitchen-sink/src/ensemble/scripts/common.js, apps/kitchen-sink/src/ensemble/scripts/test.js, packages/framework/src/evaluate/binding.ts, packages/framework/src/evaluate/evaluate.ts, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/framework/src/state/screen.ts
Added support for import scripts
Closes #523
=> feat: imports scripts

.changeset/rotten-ties-turn.md, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Search.tsx
search input infinite render
Closes #536
=> fix: search input infinite render

.changeset/healthy-boxes-boil.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/ToggleButton.tsx
=> Fix initial value of ToggleButton

.changeset/shiny-eyes-juggle.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> Expose context in executeActionGroup

packages/runtime/src/widgets/Button.tsx
=> Fix button label

apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
Added `totalRows` params in datagrid for pagination
Closes #
=> fix: added totalRows params in datagrid

.changeset/rare-ladybugs-invite.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useNavigateUrl.ts
Added argument acceptance in navigateUrl API
Closes #550
=> fix: added support of args in navigateUrl

apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/hooks/useHtmlPassThrough.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/GridView.tsx
fix illegal invocation error
Closes #
=> fix: invalid invocation error

.changeset/shy-cycles-camp.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added openUrl action for flutter compatibility
useful to open external link
https://docs.ensembleui.com/actions/open-url
Closes #556
=> feat: added openUrl action for flutter compatibility

.changeset/gold-wolves-thank.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/MultiSelect.tsx
fix search issue in multiselect
Closes #555
=> fix: search in multiselect

.changeset/curly-lions-pull.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> bind pickFiles attributes

.changeset/tricky-pianos-hug.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/invokeApi.tsx
=> bind invokeAPI name

.changeset/eleven-olives-sing.md, apps/kitchen-sink/src/ensemble/screens/layouts.yaml, packages/runtime/src/widgets/Stack.tsx, packages/runtime/src/widgets/index.ts
Added stack widget support
Closes #545
=> feat: added stack widget

.changeset/thirty-keys-fetch.md, packages/runtime/src/runtime/menu.tsx
=> Support external links in sidebar menu items

.changeset/sweet-mangos-remember.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/invokeApi.tsx
=> [HOTFIX] Restore ensemble context in ensemble.invokeAPI

.changeset/weak-shoes-accept.md, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
added curPage in dataGrid
Closes #559
=> added curPage in datagrid

.github/workflows/ci.yml, .github/workflows/release.yml, apps/preview/src/AppPreview.tsx
=> Automate react preview deploy

.github/workflows/release.yml, apps/preview/.firebaserc
=> Fix release script deploy

.changeset/old-dancers-kick.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/runtime/src/registry.tsx, packages/runtime/src/runtime/customWidget.tsx, packages/runtime/src/runtime/screen.tsx
Added support to define custom widget in screen
Closes #529
=> feat: added support to define custom widget in screen

.changeset/nervous-brooms-sip.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Form/MultiSelect.tsx, packages/runtime/src/widgets/Form/Radio.tsx, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Slider.tsx, packages/runtime/src/widgets/Switch.tsx
=> Fix enabled property of form items

.changeset/thick-pens-drive.md, packages/runtime/src/widgets/Avatar/Avatar.tsx
=> Retrofit avatar with rootRef

.changeset/clever-ways-wave.md, packages/framework/src/hooks/useHtmlPassThrough.tsx
=> Fix testid regression

.changeset/serious-rings-appear.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Form.tsx
- Bind form id
- Expose `getValues` method on form
Closes #
=> Bind form id and expose getValues method

.github/workflows/ci.yml
=> Fix ci paths-ignore

.changeset/modern-tools-tickle.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/PopupMenu.tsx
=> Add styles in popupmenu widget

.changeset/modern-scissors-care.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useShowToast.tsx
Added support of args passing and options support for position and toast type
Closes #591 #592
=> fix: added support of args passing and options support

.changeset/cold-spies-hope.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/data/index.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/parser.ts, packages/framework/src/shared/actions.ts, packages/framework/src/shared/models.ts, packages/framework/src/state/screen.ts, packages/runtime/src/runtime/hooks/useCloseAllDialogs.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/websocket.tsx
Added websocket feature
Closes #323
=> wip: websocket support

.changeset/short-swans-switch.md, packages/framework/src/parser.ts
Handle empty theme files
Closes #
=> Fix empty theme issue

.changeset/flat-melons-attend.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/navigation.tsx
Added external params in openUrl
Closes #
=> fix: added external params in openUrl

.changeset/thick-poems-exist.md, packages/runtime/src/widgets/TabBar.tsx
Added support for tabBar.selectedIndex
Closes #598
=> fix: tabBar.selectedIndex

.changeset/late-gorillas-try.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/ToggleButton.tsx
- Replace `Text` with base antd component
- Directly style text to override theme styles
- Fix icon spacing
Closes #609
=> Fix toggle button color binidngs

.changeset/real-worms-decide.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> Improve pickFiles validation

.changeset/dirty-carrots-eat.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/framework/src/data/fetcher.ts, packages/framework/src/shared/models.ts
added support for api.url, eventually will replaced with api.uri
Closes #570
=> fix: added support for api.url, eventually will replaced with api.uri

.changeset/ten-moles-dream.md, packages/framework/src/state/user.ts
Fix: ensemble.user support on widget and screen onload action
Closes #615
=> fix: ensemble.user on widget and screen load action

packages/runtime/src/widgets/Form/TextInput.tsx
=> Fix PR#308 use forEach for a string instead for ... of

.changeset/flat-spoons-dress.md, packages/runtime/src/widgets/Stepper/Stepper.tsx
=> Add onChange action in Stepper widget

.changeset/sour-ghosts-glow.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Date/Date.tsx, packages/runtime/src/widgets/Form/Form.tsx, packages/runtime/src/widgets/Form/FormItem.tsx, packages/runtime/src/widgets/Form/types.d.ts
Added support to reset forms
Closes #599
=> fix: form reset

.changeset/hungry-lamps-reply.md, packages/runtime/src/widgets/Stepper/Stepper.tsx
Recording of Stepper widget (without using any shimmers):
https://github.com/EnsembleUI/ensemble-react/assets/32386713/fed714c1-7a88-465c-abf2-20b4b683cace
Closes #
=> Delay showing stepper until its stepIndex is initialized

.changeset/afraid-rice-poke.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Form.tsx, packages/runtime/src/widgets/Form/FormItem.tsx
=> Expose submit method on form

.changeset/eight-walls-run.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/shared/ensemble.d.ts
Added support to read storage value without get method
Closes #623
=> fix: read storage without get

.changeset/violet-grapes-remain.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for id and loading params as action level
Closes #622
=> fix: added support of Id and loading params

.changeset/nervous-plums-tease.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Avatar/Avatar.tsx, packages/runtime/src/widgets/Avatar/utils/generateInitials.ts
fix `generateInitials` throwing error for strings containing white spaces
Closes #
=> Fix Avatar's inital generation logic

.changeset/cold-cameras-divide.md, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Search.tsx
Convert autocomplete widget with select widget
Closes #588
=> fix: convert autocomplete widget with select widget

.changeset/ten-flies-tie.md, packages/runtime/src/runtime/body.tsx, packages/runtime/src/runtime/entry.tsx
Added support for scrollableView
Closes #645
=> fix:  added support for scrollableView

.changeset/cyan-lizards-taste.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/FormItem.tsx
fix form field validation error message with field label
Closes #651
=> fix: form validation error message

.changeset/two-rivers-serve.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/widgets/TabBar.tsx
=> Fix tab bar selected index change with expressions

.changeset/three-terms-ring.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/shared/ensemble.d.ts
revert ensemble storage properties read method
Closes #
=> fix: revert ensemble properties read

.changeset/wicked-deers-clean.md, apps/kitchen-sink/src/App.tsx, apps/kitchen-sink/src/ensemble/screens/home.yaml, apps/kitchen-sink/src/ensemble/widgets/Button.yaml, packages/framework/src/hooks/index.ts, packages/framework/src/hooks/useEventContext.tsx, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/parser.ts, packages/framework/src/shared/actions.ts, packages/framework/src/shared/models.ts, packages/framework/src/state/screen.ts, packages/runtime/src/runtime/customWidget.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for custom events dispatch in widget
Closes #539
=> custom widget events support

.changeset/thin-lemons-study.md, packages/runtime/src/widgets/TabBar.tsx
=> Restore tab bar widget template

.changeset/hip-scissors-sparkle.md, packages/framework/src/hooks/useStyles.ts
Style priority issue, class or names will take priority compare to widget styles
Closes #647
=> fix: style priority issue

.changeset/five-shrimps-admire.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts, packages/framework/src/hooks/useStyles.ts, packages/framework/src/shared/__tests__/common.test.ts, packages/framework/src/shared/common.ts
Added support for multiple expression evaluation
Closes #
=> fix: added support for multiple expression evaluation

.changeset/slow-pugs-give.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigateExternalScreen.ts, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/modal/index.tsx, packages/runtime/src/runtime/navigation.tsx
=> Support navigation with modal screens

.changeset/metal-mugs-play.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/shared/__tests__/common.test.ts, packages/framework/src/shared/common.ts
fix combine expression checker
Closes #
=> fix: combine expression checker

.changeset/late-moose-fail.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/navigation.tsx
Added support for onModalDismiss in navigateModalScreen
Closes #672
=> fix: added support for onModalDismiss

.changeset/proud-waves-hide.md, packages/framework/src/hooks/useRegisterBindings.ts, packages/runtime/src/widgets/Form/Form.tsx
=> rebind form's methods on every render

.changeset/slimy-ducks-hear.md, packages/framework/src/i18n.ts, packages/framework/src/loader.ts
added translation support in studio
Closes #
=> fix: added translation support in studio

.changeset/empty-waves-laugh.md, packages/runtime/src/widgets/Flex.tsx
Props evaluation in flex widget
Closes #
=> fix: props evaluate in flex widget

.changeset/little-gifts-flash.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/Text.tsx
```yaml
Text:
text: ${1>1}
```
after:
before:
Closes #
=> Render boolean value in Text widget

.changeset/breezy-crabs-enjoy.md, packages/framework/src/hooks/useApplicationContext.tsx
added support for translation bundle that can accept nested json
Closes #
=> fix: added translation bundle support

.changeset/nasty-hornets-explain.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> Fix invokeAPI call order

.changeset/tender-boxes-end.md, apps/kitchen-sink/src/ensemble/screens/menu.yaml, packages/runtime/src/runtime/menu.tsx
=> feat: add visible property for sidebar menu items

.changeset/orange-rockets-agree.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Skeleton.tsx
=> feat: shape widget

.changeset/brown-shirts-argue.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/evaluate/binding.ts, packages/framework/src/evaluate/context.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/state/device.ts, packages/framework/src/state/index.ts, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
added support for device object
added propertied like, platform, width and height
Closes #676
=> fix: support device object

.changeset/moody-lobsters-occur.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Charts/LineChart.tsx, packages/runtime/src/widgets/Charts/index.tsx
Added support of filler in charts
Closes #687
=> fix: added support of filler in charts

apps/kitchen-sink/src/ensemble/screens/widgets.yaml
=> hotfix widget yaml in kitchen sink

.changeset/short-numbers-nail.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Form/Form.tsx, packages/runtime/src/widgets/Search.tsx
=> add methods updateValues in Form and onClear in Search widget

.changeset/cyan-yaks-type.md, apps/kitchen-sink/src/ensemble/config.yaml, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/framework/src/evaluate/binding.ts, packages/framework/src/evaluate/context.ts, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/shared/dto.ts, packages/framework/src/state/application.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for secrets variable
Closes #715
=> fix: added support for secrets variables

.changeset/blue-taxis-bathe.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> add visible property in DataColumns of Datagrid widget

.changeset/rotten-bugs-serve.md, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/runtime/entry.tsx
fix designated screen load on route
Closes #
=> fix: designated screen load on route

.changeset/thirty-pumpkins-remember.md, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigateModal.tsx, packages/runtime/src/runtime/navigation.tsx
=> Support opening modals/screens from the menu

.changeset/orange-mails-brake.md, apps/kitchen-sink/src/ensemble/screens/menu.yaml, packages/runtime/src/runtime/menu.tsx
=> Support styles in menu footer and header containers

packages/runtime/src/widgets/Form/Dropdown.tsx
=> Add back onItemSelect to dropdown

.changeset/heavy-cameras-fail.md, packages/runtime/src/widgets/Form/Date/Date.tsx
=> Normalize date input behavior with rest of inputs

.changeset/hungry-beers-own.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/Date/Date.tsx
=> Add format property in Date widget

.changeset/calm-fishes-camp.md, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts
home screen load issue
Closes #
=> fix: home screen load issue

.changeset/twelve-windows-love.md, packages/runtime/src/widgets/Icon.tsx
fix icon styles overload conflicts
Closes #
=> fix: icon styles overload conflicts

.changeset/nice-fireants-glow.md, packages/runtime/src/widgets/Form/Date/Date.tsx
https://github.com/user-attachments/assets/dd62d386-101d-489a-99e1-7a99336d2111
Closes #
=> remove UTC conversion from Date widget

.changeset/five-lemons-talk.md, packages/runtime/src/shared/styles.ts, packages/runtime/src/widgets/Icon.tsx
Default padding and margin format in icon
Closes #
=> fix: default padding and margin format

.changeset/tricky-deers-repeat.md, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> Add option to skip page change callback

.changeset/thin-elephants-complain.md, packages/runtime/src/runtime/menu.tsx
=> Fix pathname matching on sidebar menu

.changeset/silver-eggs-double.md, packages/runtime/src/widgets/Form/TextInput.tsx
=> fix form submission when regex is used in TextInput

.changeset/wet-baboons-glow.md, packages/runtime/src/runtime/modal/index.tsx, packages/runtime/src/runtime/navigation.tsx
=> Fix double navigate modal screen

.changeset/proud-actors-fly.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/hooks/useHtmlPassThrough.tsx, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/Date/Date.tsx, packages/runtime/src/widgets/Form/Date/DateRange.tsx, packages/runtime/src/widgets/Form/TextInput.tsx
=> Add data-testid capability to form inputs

.changeset/hot-fishes-arrive.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/Button.tsx
=> center align button's icon when no label is given

.changeset/tame-lions-cheer.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/package.json, packages/runtime/src/widgets/Form/TextInput.tsx, pnpm-lock.yaml
Relates to https://github.com/EnsembleUI/ensemble/issues/1548
=> Add maxLength and maxLengthEnforcement on text input

.changeset/neat-gifts-rescue.md, packages/framework/src/i18n.ts, packages/runtime/package.json, packages/runtime/src/widgets/Text.tsx, packages/runtime/src/widgets/__tests__/Text.test.tsx
=> Update text binding if value changes

.changeset/sour-pugs-smash.md, packages/runtime/src/runtime/navigation.tsx
=> Fallback to using action inputs if none are provided

.changeset/lemon-squids-raise.md, packages/runtime/src/widgets/Button.tsx
=> Remove unnecessary whitespace from button after antd upgrade

.changeset/swift-yaks-rush.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/TextInput.tsx
added functionality to change placeholder color
Closes #
=> fix: added functionality to change placeholder color

.changeset/config.json
Per https://github.com/changesets/changesets/issues/524
Closes #
=> Fix dependent versioning

.changeset/long-feet-relax.md, packages/framework/src/evaluate/evaluate.ts, packages/framework/src/hooks/__tests__/useRegisterBindings.test.ts, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/hooks/useRegisterBindings.ts, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/framework/src/state/screen.ts, packages/framework/src/state/widget.ts, packages/runtime/src/EnsembleApp.tsx, packages/runtime/src/runtime/entry.tsx, packages/runtime/src/runtime/header.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/hooks/useNavigateScreen.ts, packages/runtime/src/runtime/navigation.tsx
=> Small fixes for flutter interop

.changeset/fluffy-dots-share.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/__tests__/EnsembleApp.test.tsx, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/widgets/Form/Date/__tests__/Date.test.tsx, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Form/__tests__/Form.test.tsx, packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx, packages/runtime/src/widgets/__tests__/Text.test.tsx
Added inputNumber for input type number
Closes #782
=> fix: added inputNumber for input type number

.changeset/large-pots-joke.md, packages/framework/src/hooks/__tests__/useEnsembleStorage.test.ts, packages/framework/src/hooks/__tests__/useScreenData.test.ts, packages/framework/src/hooks/useEnsembleStorage.ts, packages/framework/src/state/screen.ts
=> Ensure screen and data atoms overwrite keys

packages/runtime/src/runtime/menu.tsx
=> Separate items in menu to avoid additional renders

.changeset/angry-guests-watch.md, packages/framework/src/hooks/useDeviceObserver.tsx
=> Don't update device values if value is the same

.changeset/cyan-bananas-live.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/hooks/useTemplateData.ts, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/widgets/PopupMenu.tsx, packages/runtime/src/widgets/Search.tsx
- trigger `onItemSelect` action for both `items` and `item-template`
- add trigger property (by default "click") [possible values: "click" | "hover" | "contextMenu"]
- add `enabled` and `visible` properties in popup menu item, also
- support group menu - see EDL [here](https://github.com/EnsembleUI/ensemble-react/pull/796/files#diff-b34f6a6d35e67887babd0c3fd536a7232c76aa68f211264acee0db1a58057ddeR66)
- support submenus - see EDL [here](https://github.com/EnsembleUI/ensemble-react/pull/796/files#diff-b34f6a6d35e67887babd0c3fd536a7232c76aa68f211264acee0db1a58057ddeR77)
- support context menu - see EDL [here](https://github.com/EnsembleUI/ensemble-react/pull/796/files#diff-b34f6a6d35e67887babd0c3fd536a7232c76aa68f211264acee0db1a58057ddeR170)
Closes #742
=> modernize PopupMenu widget

.changeset/healthy-readers-promise.md, packages/framework/src/hooks/__tests__/useEnsembleUser.test.ts, packages/framework/src/hooks/useEnsembleUser.ts
=> ensure user atom overwrite keys

.changeset/cyan-bananas-live.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/hooks/useTemplateData.ts, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/widgets/PopupMenu.tsx, packages/runtime/src/widgets/Search.tsx
(cherry picked from commit 69d55799aed1da2d8010e070ad99b101f079163e)
Closes #
=> Add PR796 in v0.1.x - Modernize PopupMenu Widget

.changeset/swift-elephants-mate.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, apps/kitchen-sink/src/ensemble/theme.yaml, packages/runtime/src/runtime/body.tsx
added support for screen label font color support
Closes #693
=> added support for screen level font color support

.changeset/breezy-hornets-run.md, packages/runtime/src/runtime/body.tsx
screen level style apply support
Closes #
=> hotfix: screen level style apply support

.changeset/metal-pugs-try.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
fix datagrid rows deselection issue
Closes #
=> fix: datagrid rows deselection issue

.changeset/great-pigs-attend.md, packages/runtime/src/runtime/menu.tsx
Remove navigation glitch from sidebar menu
Before:
https://github.com/user-attachments/assets/f7d28aa2-f788-42b9-be71-ea392db245f9
After:
https://github.com/user-attachments/assets/59483e88-41ee-4e54-8e21-8b9919c552b4
Closes #821
=> fix: remove navigation glitch from sidebar menu

.changeset/great-pigs-attend.md, .changeset/metal-pugs-try.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/runtime/menu.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> v0.1.x add PR # 822, 825 in v0.1.x

.changeset/popular-dryers-fold.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> fix Datagrid's defaultSelectedRowKeys

.changeset/little-cheetahs-bake.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/shared/actions.ts, packages/runtime/src/runtime/hooks/useCloseAllModalScreens.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/runtime/modal/index.tsx
Added support for close all navigate modal screens
Closes #
=> fix: added support for close all navigate modal screens

.changeset/weak-rocks-do.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/QrCode.tsx, packages/runtime/src/widgets/index.ts
Added support for qrcode widget
Closes #828
=> fix: added support for qrcode widget

.changeset/modern-ladybugs-sing.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/package.json, packages/runtime/src/widgets/Form/TextInput.tsx, pnpm-lock.yaml
Added mask format support in textInput
https://github.com/user-attachments/assets/554a817e-d505-40a1-b5e1-9e464afa821c
Closes #835
=> fix: added support for mask textInput

.changeset/thin-rules-carry.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Slider.tsx
Added range support in slider
Closes #789
=> added range support in slider

.changeset/stale-hounds-tickle.md, packages/framework/src/parser.ts, packages/framework/src/shared/models.ts, packages/runtime/src/runtime/__tests__/screen.test.tsx, packages/runtime/src/runtime/customWidget.tsx, packages/runtime/src/runtime/screen.tsx
=> Declare screen inputs even if they are not passed in with value

.changeset/unlucky-bugs-tie.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, apps/kitchen-sink/src/ensemble/scripts/common.js, packages/runtime/src/widgets/Form/FormItem.tsx
Closes #
https://github.com/EnsembleUI/ensemble-react/pull/838
=> fix form item's label not picking evaluated value

.changeset/small-rules-notice.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/runtime/hooks/useNavigateModal.tsx
=> add ensemble.user and ensemble.env context in navigateModalScreen hook

.changeset/violet-meals-roll.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/framework/src/hooks/useTemplateData.ts, packages/runtime/src/widgets/Form/Radio.tsx
Added item-template support in Radio widget
Closes #817
=> feat: modernaization radio widget

.changeset/sharp-walls-repeat.md, packages/runtime/src/widgets/Form/TextInput.tsx
fix mask input required validation
Closes #857
=> fix: mask input required validation

.gitattributes, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/framework/src/shared/actions.ts, packages/runtime/package.json, packages/runtime/src/runtime/hooks/__tests__/useEnsembleAction.test.tsx
=> [840] Support directly writing code without `executeCode` action.

.changeset/smooth-games-rule.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Collapsible.tsx
Change collapsible widget name with accordion and change isAccordion prop with limitExpandedToOne
Closes #863
=> fix: change collapsible widget name

.changeset/tame-news-drum.md, packages/runtime/src/widgets/Text.tsx
=> Initialize text with binding

.changeset/old-impalas-knock.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/Button.tsx, packages/runtime/src/widgets/__tests__/Button.test.tsx
Button loader binding evaluation
Closes #873
=> fix: button loader binding evaluation

.changeset/many-cats-fold.md, packages/runtime/src/widgets/Form/FormItem.tsx, packages/runtime/src/widgets/Form/__tests__/Form.test.tsx
improved required error message
before
after
Closes #876
=> fix: improved required error message

.changeset/short-pigs-check.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/ToolTip.tsx, packages/runtime/src/widgets/index.ts
Added tooltip widget
Closes #875
=> fix: added tooltip widget

.changeset/spotty-needles-check.md, packages/runtime/src/widgets/ToggleButton.tsx
Before:
https://github.com/user-attachments/assets/419c9ac8-28f2-4ac9-b546-6ee3d7128457
After:
https://github.com/user-attachments/assets/bbe20f62-acda-4551-a254-3b47f42ab8ff
Closes #
=> Initialize ToggleButton with binding

.changeset/light-balloons-juggle.md, packages/runtime/src/widgets/Form/TextInput.tsx
fix paste data on mask pattern update value
Closes #878
=> fix: mask property not working

.changeset/great-rats-crash.md, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Adds file input element to DOM so UI automation can interact with it
Closes #888
=> Append file input element in document body for UI automation

.changeset/ten-lobsters-relax.md, .github/workflows/ci.yml
=> Automate release changes

.changeset/chilled-books-give.md, packages/framework/src/data/fetcher.ts, packages/framework/src/hooks/useCommandCallback.ts, packages/framework/src/shared/actions.ts, packages/framework/src/shared/common.ts, packages/runtime/src/runtime/hooks/useNavigateUrl.ts
=> improve performance of navigateUrl action

.changeset/tall-coins-think.md, packages/cli/package.json, pnpm-lock.yaml
=> Fix CLI dependencies

.changeset/purple-dodos-behave.md, packages/cli/package.json, pnpm-lock.yaml
=> Fix CLI dependencies pt2

.changeset/hip-bananas-decide.md, packages/runtime/src/widgets/Search.tsx
UseCase:
allow user to pass a custom widget for selected option
https://github.com/user-attachments/assets/9affdb46-91fc-4b85-8ff5-dad2b9cf24e8
Closes #
=> expose selectedLabel prop in Search component

.changeset/nice-socks-watch.md, packages/runtime/src/widgets/Tag.tsx
=> Removed default pointer cursor from Tag widget

.changeset/bright-walls-reply.md, packages/framework/src/hooks/useApplicationContext.tsx, packages/framework/src/hooks/useCommandCallback.ts, packages/framework/src/hooks/useScreenContext.tsx, packages/framework/src/hooks/useThemeContext.tsx, packages/framework/src/shared/ensemble.d.ts, packages/framework/src/state/application.ts, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added missing themeContext in useCommandCallback
Closes #
=> missing theme context in useCommandCallback

.changeset/tame-carrots-lick.md, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Search.tsx
=> 921 allow default value for search widget

.changeset/tame-eyes-care.md, apps/kitchen-sink/src/ensemble/screens/home.yaml, packages/runtime/src/widgets/Carousel.tsx
=> fix: carousal widget

.changeset/cuddly-games-hope.md, .changeset/warm-sloths-drive.md, apps/kitchen-sink/src/ensemble/widgets/Header.yaml, packages/runtime/src/widgets/Search.tsx
Closes https://github.com/EnsembleUI/ensemble-react/issues/926
=> search widget with preload results

.changeset/thin-turkeys-love.md, packages/js-commons/src/local-files.ts, packages/js-commons/src/transporter.ts
=> Export local global app metadata

.changeset/itchy-zoos-chew.md, packages/js-commons/src/local-files.ts
=> Fixes for offline

.changeset/cyan-fans-sort.md, packages/js-commons/src/local-files.ts
=> Handle edge cases in document intake

.github/workflows/ci.yml, .github/workflows/release.yml
=> Fix release workflow

.changeset/dirty-ways-remember.md, packages/cli/src/firebase.ts, packages/js-commons/package.json, packages/js-commons/src/core/firebase.ts
=> Use regular firebase instead of firebase lite

.changeset/grumpy-bags-change.md, packages/js-commons/src/core/dto.ts, packages/js-commons/src/core/firebase.ts
=> Fix issues with push and pull for studio

.changeset/lucky-seahorses-cough.md, packages/js-commons/src/core/firebase.ts, packages/js-commons/src/core/service.ts
=> Add history entry when pushing apps

.changeset/yellow-avocados-fold.md, packages/runtime/src/widgets/Form/MultiSelect.tsx, packages/runtime/src/widgets/Form/__tests__/MultiSelect.test.tsx
added support for object in values in multiselect
Closes #914
=> fix: added support for object in values in multiselect

.changeset/lazy-lemons-breathe.md
Closes #
https://github.com/EnsembleUI/ensemble-react/pull/937
=> add changeset missed in PR#937

.changeset/chilled-papayas-wink.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/ToggleButton.tsx
=> add multiple selection support in ToggleButton widget

.changeset/early-boats-bathe.md, packages/runtime/src/widgets/QrCode.tsx
Show evaluated values in qrcode widget
Closes #
=> fix: show evaluated values in qrcode widget

.changeset/curvy-moles-attend.md, packages/js-commons/src/core/local-files.ts, packages/js-commons/src/core/transporter.ts
=> add method for deleting ensemble app locally

.changeset/afraid-garlics-joke.md, packages/js-commons/src/core/firebase.ts, packages/js-commons/src/core/local-files.ts, packages/js-commons/src/core/service.ts
https://github.com/user-attachments/assets/dc6ffe5c-c998-4bc0-a4ef-fe396e717ff6
Closes #
=> Enhance application transporters to handle assets and fonts

.changeset/big-beds-rest.md, packages/framework/src/evaluate/binding.ts, packages/framework/src/state/screen.ts, packages/runtime/package.json, packages/runtime/src/widgets/DataGrid/DataCell.tsx, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/PopupMenu.tsx, pnpm-lock.yaml
- Optimizes data cell rendering with memo and `shouldCellUpdate`
- Removes hard dependency on screenData atom in bindings, replacing it with dynamic atom based on API identifier
- Prevents propagation in PopupMenu trigger element to simplify widget YAML
Closes #
=> Grid performance improvements

.changeset/blue-cheetahs-deliver.md, packages/runtime/src/runtime/hooks/__tests__/useEnsembleAction.test.tsx, packages/runtime/src/runtime/hooks/useNavigateScreen.ts
fix: evaluation of navigateScreen
Closes #
=> fix: evaluation of navigateScreen

.changeset/stale-colts-pretend.md, packages/runtime/src/widgets/PopupMenu.tsx
=> Prevent propagation of popup menu items

.changeset/neat-ads-eat.md, packages/framework/src/evaluate/context.ts, packages/framework/src/hooks/useEvaluate.ts, packages/framework/src/state/application.ts, packages/runtime/src/widgets/DataGrid/DataGrid.tsx, packages/runtime/src/widgets/Form/__tests__/MultiSelect.test.tsx
=> Improve grid rendering at large volumes

.changeset/heavy-foxes-deny.md, packages/framework/src/hooks/useCustomScope.tsx, packages/framework/src/hooks/useEvaluate.ts
=> Copy custom scope objects when propagating to bindings

.changeset/rich-rice-dream.md, packages/framework/src/hooks/useEvaluate.ts, packages/framework/src/shared/__tests__/common.test.ts, packages/framework/src/shared/common.ts, packages/runtime/src/runtime/__tests__/customWidget.test.tsx
=> Fix custom widget regression and add tests

.changeset/tough-boats-bathe.md, apps/kitchen-sink/src/ensemble/screens/actions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/__tests__/Button.test.tsx
Added support for reset pickFiles
Closes #998
=> 998-added-support-for-reset-pickFile

.changeset/popular-pens-juggle.md, packages/runtime/src/runtime/hooks/__tests__/useUploadFile.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/__tests__/Button.test.tsx
Added useCommandCallback in uploadFiles
Closes #
=> fix: added useCommandCallback in uploadFiles

.changeset/dirty-otters-camp.md, packages/framework/src/hooks/useScreenData.ts, packages/runtime/src/runtime/hooks/__tests__/useInvokeApi.test.tsx
fix: api state reflect on useScreenData and screenData atom
Closes #995
=> fix: api state reflect

.changeset/hungry-teachers-cheat.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/MultiSelect.tsx, packages/runtime/src/widgets/Form/__tests__/MultiSelect.test.tsx
=> enhance MultiSelect component with maxCount, maxTagCount, and maxTagTextLength props

.changeset/ninety-birds-kneel.md, packages/runtime/src/widgets/Collapsible.tsx, packages/runtime/src/widgets/__tests__/Collapsible.test.tsx
fix templateDate re-render issue in collapsible
Closes #
=> fix: templatedata re-render issue in collapsible

.changeset/popular-badgers-cheer.md, packages/runtime/src/runtime/hooks/__tests__/useUploadFile.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
evaluate uploadAPI inputs
Closes #
=> fix: evaluate uploadAPI inputs

.changeset/heavy-coins-greet.md, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Form/__tests__/Form.test.tsx
avoid empty field validation
Closes #
=> fix: avoid empty field validatation

.changeset/flat-beds-repeat.md, packages/js-commons/src/core/local-files.ts
filename extension for scripts is .yaml too. this PR changes it to .js
Closes #
=> update filename extension for script artifacts

.changeset/silent-toes-look.md, packages/runtime/src/widgets/Icon.tsx
=> prevent event propagation on icon click

.changeset/eight-ads-argue.md, apps/preview/src/AppPreview.tsx
fix: ensemble preview breaking change
Closes #
=> fix: ensemble preview handle

.changeset/shaggy-lamps-pay.md, packages/runtime/src/widgets/Form/MultiSelect.tsx
=> expose notFoundContent property for MultiSelect widget

.changeset/few-scissors-confess.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/widgets/Form/TextInput.tsx, packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx
=> add onKeyDown action in TextInput widget

.changeset/nasty-cats-dress.md, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> always show pagination options in DataGrid widget

.changeset/twenty-lamps-help.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/PopupMenu.tsx
=> support onTriggered action in PopupMenu widget

.changeset/few-tables-shake.md, apps/kitchen-sink/src/ensemble/screens/testActions.yaml, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> fix: error message handler in useUploadFile action

.changeset/cyan-shoes-speak.md, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
=> improve file extension validation in pickFiles action by normalizing case

.changeset/honest-gorillas-care.md, apps/kitchen-sink/src/ensemble/screens/testActions.yaml, packages/framework/src/evaluate/evaluate.ts, packages/runtime/src/runtime/hooks/__tests__/useEnsembleAction.test.tsx, packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx, packages/runtime/src/runtime/hooks/useEnsembleAction.tsx, packages/runtime/src/widgets/__tests__/Button.test.tsx
=> fix: added support for await in executeCode

.changeset/giant-owls-exercise.md, packages/js-commons/package.json, packages/js-commons/src/core/local-files.ts, pnpm-lock.yaml
https://github.com/user-attachments/assets/ea84f20a-e8e9-4333-ade3-08451c3e7d22
Closes https://github.com/EnsembleUI/ensemble-web-studio/issues/1625
=> get deterministic serialization using stableStringify

.changeset/thin-horses-breathe.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/shared/styles.ts, packages/runtime/src/widgets/Form/Dropdown.tsx, packages/runtime/src/widgets/Form/MultiSelect.tsx
=> fix applying Dropdown and MultiSelect selector styles

.changeset/brave-trees-smile.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/DataGrid/DataGrid.tsx
=> DataRow styles with context

.changeset/bright-bugs-beg.md
=> feat: add patch versions for react-kitchen-sink and react-runtime for stepper jumps

.changeset/lovely-dancers-admire.md, apps/kitchen-sink/src/ensemble/screens/widgets.yaml, packages/runtime/src/widgets/Form/Checkbox.tsx, packages/runtime/src/widgets/Form/Dropdown.tsx
=> fix search in Dropdown when autoComplete is used

.changeset/tame-onions-lick.md, apps/kitchen-sink/src/ensemble/screens/forms.yaml, packages/runtime/src/runtime/modal/index.tsx
=> ensure navigateModalScreen supports custom widget title
