- .changeset/chatty-points-occur.md
- .changeset/rich-kiwis-switch.md
- apps/starter/craco.config.js
- apps/starter/src/ensemble/screens/usersAndGroups.yaml
- apps/starter/src/index.tsx
- packages/framework/src/evaluate.ts
- packages/framework/src/hooks/useRegisterBindings.ts
- packages/framework/src/hooks/useScreenContext.tsx
- packages/framework/src/hooks/useWidgetState.ts
- packages/framework/src/state/screen.ts
- packages/framework/src/state/widget.ts
- packages/runtime/package.json
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- packages/runtime/src/widgets/GridView.tsx
- pnpm-lock.yaml
- Ensures undefined widget keys don't override data context keys in evaluation scope
- Fix invokeApi callbacks firing twice by keeping track of completion state
- Only store states for widgets with explicit IDs to improve performance
Closes #207
> Only store states for widgets with explicit IDs to improve performance

- .changeset/dirty-plums-ring.md
- packages/runtime/src/runtime/customWidget.tsx
- Use useRegisterBindings to evaluate expressions in inputs before being passed to custom widget
Closes #208
> Register custom widget inputs as bindings

- apps/starter/src/ensemble/screens/usersAndGroups.yaml
- packages/framework/src/hooks/useTemplateData.ts
- packages/runtime/src/widgets/Column.tsx
- packages/runtime/src/widgets/Row.tsx
- Added support for one level deep nested item-templates 
```yaml
- Column:
item-template:
data: ensemble.storage.get("arrayOfUsers")
name: usr
template:
Row:
gap: 5
children:
- Text:
text: ${usr.fields.name}
- Column:
item-template:
data: usr.fields.groups
name: n1
template:
Text:
text: ${n1}
```
Closes #
> Added ability to cater nested item-templates

- .changeset/olive-cougars-draw.md
- apps/starter/package.json
- packages/runtime/src/widgets/Dropdown.tsx
- Handles nullable item template in dropdown that was creating regression
Closes #
> [Hotfix] handle nullable item template in dropdown

- .changeset/afraid-days-sniff.md
- apps/kitchen-sink/src/ensemble/screens/layouts.yaml
- packages/runtime/src/widgets/Button.tsx
Added stop event propagation in button onTap action
When we put the button on the collapsible header and when we click on the button, it execute the callback of the button, but it also collapse the collapsible item. so to prevent that behaviour, I added stop event propagation in button callback
Closes #
> added stop event propagation

- .changeset/famous-fans-compare.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/DataGrid/DataGrid.tsx
Added feature for enable stickey header and footer in data grid widget
Closes #
closes #364
> fix: added stickey header and footer in data grid

- .changeset/chilly-dragons-kneel.md
- packages/runtime/src/index.tsx
- packages/runtime/src/runtime/hooks/index.ts
`useEnsembleAction` hook does not become the part of build. Need to use it to implement action in a custom widget implementation on customer app.
> expose useEnsembleAction hook for outer world

- .changeset/great-mails-complain.md
- packages/framework/src/hooks/useRegisterBindings.ts
Add force option in useRegisterBindings hook
React component using useRegisterBindings hook was not being re-rendered properly when re-mounted with same values. 
Closes #
> Add force option to useRegisterBindings hook

- .changeset/big-ghosts-fold.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/Form/Dropdown.tsx
to fix delay in initial loaded value with the right option, only allow dropdown render once options are loaded
Closes #470
> fix: only render dropdown after options render

- .changeset/poor-numbers-buy.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/MultiSelect.tsx
Added condition to disable free text entry in multiselect
Closes #518
> fix: added condition to disable free text entry

- .changeset/tender-students-doubt.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/DataGrid/DataGrid.tsx
Added support for onSort action handler in datagrid widget
Closes #513
> fix: added support for onSort action handler in datagrid

- .changeset/eighty-roses-accept.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/DataGrid/DataGrid.tsx
- Added ability for users to have defaultRowSelection 
Closes #
> Added defaultSelection ability

- .changeset/orange-planets-fail.md
- apps/kitchen-sink/src/ensemble/widgets/Header.yaml
- packages/runtime/src/widgets/Search.tsx
- Makes the output of onSelect symmetrical with the data binding coming in. Works around the restriction of AntD requiring that options have unique values (which objects are not accepted for)
- Skips client side filtering if onSearch callback is provided since we can assume the onSearch callback is doing the result filtering
Closes #
> Make Search widget symmetrical

- .changeset/silent-melons-rescue.md
- packages/runtime/src/runtime/modal.tsx
fix showDialog's height to whatever user has given - `height:100%` inside options of showDialog was not working
refer to working of this showDialog https://github.com/EnsembleUI/ensemble-react/blob/2fd6f41dfbff187596e0763d3d74606cf2b8af0e/apps/kitchen-sink/src/ensemble/screens/actions.yaml#L250-L256
Closes #
> Fix showDialog's height to whatever user has given

- packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- packages/runtime/src/runtime/invokeApi.tsx
Remove evaluate from ensemble.invokeAPI as that was unnecessary.
Closes #514
> fix: remove evaluate from ensemble.invokeAPI

- .changeset/thirty-wolves-carry.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/Button.tsx
Added loading attribute in button.
Can set loading attribute by two way
1. by setting `loading` attribute in EDL
2. by setting `setLoading` through `executecode`
Example:
```yaml
Button:
label: toggle
loader: ${ensemble.storage.get('loaderStat')}
```
```yaml
onTap:
executeCode: |
toggleButton.setLoading(true)
```
https://github.com/EnsembleUI/ensemble-react/assets/31651612/c2dc5096-302b-43dc-99fc-1ae9ac302b99
Closes #
> fix: added loading attribute in button

- .changeset/strange-pumpkins-brake.md
- packages/runtime/src/widgets/Search.tsx
Reset options when there are no options on search query
Closes #
> fix: reset options when there are no options on search query

- .changeset/clever-phones-play.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/Date/Date.tsx
When `value: ''` or `value: null` is passed in EDL of Date widget, we show just the hintText instead of "Invalid Date" so that 
1. picker is in workable
2. we can initialize Date widget with empty selected date by default (need in Atlas in manager filters)
Before:
https://github.com/EnsembleUI/ensemble-react/assets/32386713/3c40eea1-766a-44a0-8b20-f5d021608150
After:
https://github.com/EnsembleUI/ensemble-react/assets/32386713/e04defc2-c6c0-42f8-af60-ae4f9137502b
Closes #
> Show just the hintText in case of empty value of Date widget

- .changeset/ninety-bats-taste.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/TabBar.tsx
Added support to choose tabBar stretch option
Closes #593
> fix: tabBar stretch options

- .changeset/neat-books-carry.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/FormItem.tsx
- packages/runtime/src/widgets/Form/TextInput.tsx
- packages/runtime/src/widgets/Form/types.d.ts
- support inputType, validator and mask on TextInput widget
- support validateOnUserInteraction on form items
https://github.com/EnsembleUI/ensemble-react/assets/32386713/555fcc04-a6d4-453d-95e7-c5330e05a932
Closes #616
> 616 need support for inputtype and validator in textinput widget

- .changeset/tricky-elephants-wait.md
- packages/runtime/src/runtime/customWidget.tsx
Added support for widget input intialized
Closes #590
> fix: widget input initialized supports

- .changeset/dry-colts-search.md
- packages/runtime/src/runtime/modal.tsx
- packages/runtime/src/runtime/modal/index.tsx
- packages/runtime/src/runtime/modal/utils.ts
Opening a modal currently re-renders any component that uses the context (from actions) because the modal context value is always a new object.
Solution here is to memoize the model context API object.
Closes #648
> Memoize modal API to avoid re-renders on registered actions

- .changeset/shiny-singers-shout.md
- apps/kitchen-sink/src/ensemble/config.yaml
- apps/kitchen-sink/src/ensemble/screens/home.yaml
- packages/framework/src/evaluate/binding.ts
- packages/framework/src/evaluate/context.ts
Added support for access environment variables through env
example
```yaml
- Text:
text: ${env.randomId}
```
Closes #
> fix: added support for access environment variables through env

- .changeset/weak-rats-work.md
- packages/runtime/src/widgets/Form/Date/Date.tsx
https://github.com/EnsembleUI/ensemble-react/assets/32386713/3e0092b1-96ab-41ba-8038-2fd88f98ab85
https://github.com/EnsembleUI/ensemble-react/assets/32386713/904211db-5384-4871-806a-dc5ed38e47d5
Closes #
> Date widget: fix setting state value to binding value on subsequent load of widget

- .changeset/short-pens-flash.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/Collapsible.tsx
Added 3 header styles to the Collapsible widget: textColor, borderColor, and borderWidth. Also created a getHeaderStyles function that renames some of the header styles as I did not like the default names that Ant Design gave to them.
[Issue #692
](https://github.com/EnsembleUI/ensemble-react/issues/692)
Closes #692 
- [ ✅] I have performed a self-review of my code
- [ ✅] I have added tests
- [ ✅] I have added a changeset `pnpm changeset add`
- [ ✅] I have added example usage in the kitchen sink app
> 692 support additional styles on collapsible header especially color

- .changeset/lazy-snails-sniff.md
- apps/kitchen-sink/src/ensemble/screens/menu.yaml
- packages/runtime/src/runtime/entry.tsx
- packages/runtime/src/runtime/menu.tsx
1. don't route when page/url is not given in menu
2. revert back exposed method from `setIsCollapsed` to `setCollapsed` which got added [here](https://github.com/EnsembleUI/ensemble-react/pull/744/files#diff-698b21689b3e129055e1704ea4e6aa532839d68b2a24af0cffa1f1adc5136379R101)
3. remove unused `enableSearch` prop
4. make `icon` prop optional
https://github.com/user-attachments/assets/56831c4f-feab-4e10-bd33-3cb81239d4f6
Closes #
> fix: don't route when page/url is not given in menu

- .changeset/sharp-mugs-yawn.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/framework/src/hooks/useWidgetId.ts
- packages/runtime/src/runtime/modal/index.tsx
- packages/runtime/src/runtime/modal/utils.ts
problem: when a dialog/modal screen is opened from within a modal screen, the styles of top most dialog/modal are being used in existing ones too.
https://github.com/user-attachments/assets/c30b2b70-d506-478a-99de-1faba465a69b
https://github.com/user-attachments/assets/ba909433-cd24-40d4-9af6-f8c8a222d286
Closes #
> Use unique key when applying styles to modal

- .changeset/many-days-sip.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/TextInput.tsx
**Problem:**
regex: `.{1,}` does not work for "atleast 1 character" when there's no input entered by user - and form is submitted.
**Solution:**
when there's no input entered by user, treat `undefined` value of TextInput as empty string so that regex can be validated successfully.
Closes #
> fix TextInput's regex validator not validating on no input

- .changeset/funny-cobras-approve.md
- packages/framework/src/hooks/useApplicationContext.tsx
- packages/runtime/src/widgets/Charts/index.tsx
load first theme as default from theme yaml
Closes #
> fix: choose first theme as default from the theme yaml and add theme in charts

- .changeset/strange-impalas-act.md
- packages/runtime/src/widgets/Form/Dropdown.tsx
Improve dropdown performance, previously it was in infinite loop and consume large memory of browser tab
Closes #
> fix: improve dropdown panel performance

- .changeset/chatty-icons-burn.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- apps/kitchen-sink/src/ensemble/widgets/StyledText.yaml
- packages/framework/src/api/data.ts
- packages/framework/src/api/index.ts
- packages/framework/src/api/modal.ts
- packages/framework/src/api/navigate.tsx
- packages/framework/src/evaluate/binding.ts
- packages/framework/src/evaluate/context.ts
- packages/framework/src/evaluate/evaluate.ts
- packages/framework/src/hooks/index.ts
- packages/framework/src/hooks/useCommandCallback.ts
- packages/framework/src/hooks/useScreenContext.tsx
- packages/framework/src/shared/ensemble.d.ts
- packages/framework/src/state/screen.ts
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- packages/runtime/src/runtime/locationApi.tsx
Refactors useExecuteCode dependencies to be fetched at execution instead of re-render, which should greatly improve performance. This required refactoring a bunch of dependencies into framework project and needs to be cleaned up further.
Closes #
> Refactor useExecuteCode to leverage atomCallback

- .changeset/giant-laws-know.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/FormItem.tsx
Added fix for show only one error message on form field for validate
Before
After
Closes #837
> only show one error message at a time in form fields

- .changeset/funny-hotels-love.md
- apps/preview/src/App.tsx
- apps/preview/src/AppPreview.tsx
- packages/framework/src/hooks/useApplicationContext.tsx
- packages/framework/src/hooks/useFonts.ts
- packages/framework/src/loader.ts
- packages/framework/src/parser.ts
- packages/framework/src/shared/dto.ts
- packages/framework/src/shared/models.ts
- packages/framework/tsconfig.json
- packages/tsconfig/react-library.json
Added support for custom fonts in ensemble studio
1. uploaded font
2. added classname (`topHeader`) in screen
3. added style (`fontFamily` in `topHeader` class) to class in theme
4. output
Closes #762
> fix: added support for custom fonts in ensemble studio

- .changeset/happy-pears-suffer.md
- packages/runtime/src/widgets/Button.tsx
Previously when button in placed in showDialog and start the loader of button, then close the dialog and open again, the button widget will be traped inside infinite re-render
before
https://github.com/user-attachments/assets/8f4abffa-0a49-4682-a7e5-20237f7a83fa
after
https://github.com/user-attachments/assets/44e3a900-625c-4a1b-b0d0-01e7a0b3740d
Closes #
> fix: button loader on component re-initialized

- .changeset/afraid-bikes-poke.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- packages/runtime/src/widgets/Form/TextInput.tsx
- packages/runtime/src/widgets/Form/__tests__/TextInput.test.tsx
Added support for decimal in textInput number
Closes #868
> fix: added support for decimal in textInput number

- .changeset/odd-eagles-whisper.md
- packages/runtime/src/widgets/DataGrid/DataGrid.tsx
> remove default scrollHeight in Datagrid to get rid of unwanted vertical scrollbar

- .changeset/big-owls-whisper.md
- packages/runtime/src/widgets/Search.tsx
#906 
https://github.com/user-attachments/assets/e8ae35d2-2de8-4106-8349-c61316413a58
Closes #
> [906] chore: clear search results when focused outside the Search widget

- .changeset/fluffy-islands-act.md
- apps/kitchen-sink/src/ensemble/screens/home.yaml
- packages/runtime/src/runtime/hooks/__tests__/useActionGroup.test.tsx
- packages/runtime/src/runtime/hooks/__tests__/useEnsembleAction.test.tsx
- packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for await in executeCodeBlock
Closes #638
> fix: added support for await in executeCodeBlock

- .changeset/early-dryers-drum.md
- apps/kitchen-sink/src/ensemble/screens/home.yaml
- packages/framework/package.json
- packages/framework/src/api/data.ts
- packages/framework/src/shared/api.ts
- packages/framework/src/shared/index.ts
- packages/framework/src/shared/models.ts
- packages/runtime/package.json
- packages/runtime/src/EnsembleApp.tsx
- packages/runtime/src/runtime/hooks/__tests__/useActionGroup.test.tsx
- packages/runtime/src/runtime/hooks/__tests__/useInvokeApi.test.tsx
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
- pnpm-lock.yaml
fix added cache support in API trigger
Closes #350
> fix: added cache in API call

- .changeset/fluffy-apes-kick.md
- packages/runtime/src/widgets/Search.tsx
Instead of setting the unparsed initial value, set the parsed initial value from the registered bindings.
Closes #
> [921] fix: register initialValue binding for Search widget

- .changeset/good-chicken-wonder.md
- packages/framework/src/shared/__tests__/common.test.ts
- packages/framework/src/shared/common.ts
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Improve regex of replacer in evaluateDeep
The current regex is not capable to evaluate `${ensemble.user.userDetails?.clients?.map(({id}) => id) ?? []}`
Closes #
> fix: improve regex of replacer in evaluateDeep

- .changeset/brave-geckos-deny.md
- packages/runtime/src/runtime/hooks/__tests__/useInvokeApi.test.tsx
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
prevent modalContext override in API response handler
Closes #
> fix: prevent modalContext override in API response handler

- .changeset/tidy-pants-kiss.md
- apps/kitchen-sink/src/ensemble/screens/home.yaml
- packages/framework/src/api/data.ts
- packages/framework/src/hooks/useCommandCallback.ts
- packages/framework/src/shared/actions.ts
- packages/runtime/src/runtime/hooks/__tests__/useExecuteCode.test.tsx
- packages/runtime/src/runtime/hooks/__tests__/useInvokeApi.test.tsx
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
Added support for forceRefresh cache in invokeAPI
Closes #990
> fix: added support for forceRefresh cache in invokeAPI

- .changeset/spotty-games-battle.md
- packages/js-commons/src/core/dto.ts
- packages/js-commons/src/core/firebase.ts
https://github.com/user-attachments/assets/b3d25225-e24e-4243-bd69-8f1ef71794e8
https://github.com/user-attachments/assets/0bcef11a-cf9f-4397-9c81-f652dc9c91b4
Closes #
> add secrets support in firestore app transporter

- .changeset/gorgeous-apes-sing.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/DataGrid/DataGrid.tsx
before adding `selectionColWidth` property
after adding `selectionColWidth` property
Closes #1033
> feat: add selection column width property to DataGrid

- .changeset/serious-wasps-agree.md
- apps/kitchen-sink/src/ensemble/screens/widgets.yaml
- packages/runtime/src/widgets/Form/Dropdown.tsx
> feat: add option to allow clearing selection in dropdown

- .changeset/modern-points-attack.md
- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- .github/workflows/release.yml
- packages/js-commons/src/core/local-files.ts
1.
Remove `projectPath` from `.manifest` file of an app
Fetch projectPath value from global manifest file
2.
https://github.com/FirebaseExtended/action-hosting-deploy#firebasetoolsversion-string
https://github.com/firebase/firebase-tools/releases
Closes https://github.com/EnsembleUI/ensemble-web-studio/issues/1617
> use relative paths in app's manifest file

- .changeset/light-years-do.md
- apps/kitchen-sink/src/ensemble/screens/testActions.yaml
- packages/framework/src/api/index.ts
- packages/framework/src/api/toast.ts
- packages/framework/src/hooks/useCommandCallback.ts
- packages/framework/src/shared/ensemble.d.ts
- packages/runtime/src/runtime/hooks/useEnsembleAction.tsx
> support showToast action via code

- .changeset/new-trees-wonder.md
- apps/kitchen-sink/src/ensemble/screens/forms.yaml
- apps/kitchen-sink/src/ensemble/screens/home.yaml
- packages/runtime/src/widgets/Form/MultiSelect.tsx
- packages/runtime/src/widgets/Form/__tests__/MultiSelect.test.tsx
> Support item-template in MultiSelect widget

- .changeset/gentle-countries-teach.md
- packages/framework/jest.config.js
- packages/framework/setupTests.ts
- packages/framework/src/hooks/__tests__/screenHydrationNoClobber.test.tsx
- packages/framework/src/hooks/__tests__/useEnsembleUser.test.ts
- packages/framework/src/hooks/__tests__/userAtomSync.test.tsx
- packages/framework/src/hooks/useCommandCallback.ts
- packages/framework/src/hooks/useEnsembleUser.ts
- packages/framework/src/hooks/useScreenContext.tsx
- packages/framework/src/state/user.ts
- packages/framework/tsconfig.json
This PR fixes the issue where we're getting stale properties via ensemble.user api such as accessToken in the app.
Closes #
> fix stale values in ensemble.user

- .changeset/tasty-taxis-appear.md
- packages/runtime/src/widgets/PopupMenu.tsx
> optimize PopupMenu with memoization and lazy rendering

- .changeset/thin-pens-push.md
- packages/runtime/src/widgets/Button.tsx
> enhance Button's label check before unwrapping it
